language: python
python:
    - "2.7"
    - "3.3"
    
env:
    - DJANGO_VERSION=1.6

install:
    - pip install argparse
    
    - pip install -q Django==$DJANGO_VERSION
    
    - pip install coverage

    - pip install pep8
    - pip install pyflakes

before_script:
    - "pep8 --ignore=E501 pyfreebilling"
    - pyflakes pyfreebilling
    
script:
    - coverage run quicktest.py pyfreebilling    
    
    - pip install -r requirements/requirements.txt
    - python manage.py syncdb
    - python manage.py migrate
    
after_success:
  - pip install coveralls
  - coveralls
