language: python
python:
    - "2.7"
    - "3.3"
    
env:
    - DJANGO_VERSION=1.6

before_install:
  # get the C part of the GeoIP API
    - wget https://github.com/maxmind/geoip-api-c/releases/download/v1.6.9/GeoIP-1.6.9.tar.gz
    - tar xzf GeoIP-1.6.9.tar.gz
    - cd GeoIP-1.6.9
    - ./configure --prefix /opt/geoip-1.6.9
    - make
    - make check  #     (Used to have some errors, but not in 1.6.9)
    - sudo make install

  # get the GeoIP database needed for the tests
    - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
    - gunzip GeoIP.dat.gz
    - sudo mkdir -p /opt/geoip-1.6.9/share/GeoIP/
    - sudo mv GeoIP.dat /opt/geoip-1.6.9/share/GeoIP/GeoIP.dat
    - cd ..

install:
    - pip install argparse

    - pip install -U setuptools
    
    - pip install -q Django==$DJANGO_VERSION
    
    - pip install coverage

    - pip install pep8
    - pip install pyflakes

before_script:
    - "pep8 --ignore=E501,E127,E128,E123,E226,E502 pyfreebilling"
    
script:
    - coverage run quicktest.py  
    
    - pip install -r requirements/requirements.txt
    - python manage.py syncdb
    - python manage.py migrate
    
after_success:
    - pip install coveralls
    - coveralls
