language: python
python:
    - "2.7"
    - "3.3"
    
env:
    - DJANGO_VERSION=1.6

install:
    - pip install argparse --use-mirrors
    
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    
    - pip install coverage

    - pip install pep8 --use-mirrors
    - pip install pyflakes --use-mirrors

before_script:
    - "pep8 --ignore=E501 {{APP_NAME}}"
    - pyflakes {{APP_NAME}}
    
script:
    - coverage run quicktest.py {{APP_NAME}}    
    
    - pip install -r requirements/requirements.txt
    - python manage.py syncdb
    - python manage.py migrate
    
after_success:
  - pip install coveralls
  - coveralls
